const EN_READING = [
  'Free trade is an economic policy under which the government does not interfere with trade. No tariffs are applied to imports or exports, and people are allowed to trade goods and services as they please.',
  'The problem begins with the alphabet itself. Building a spelling system for English using letters that come from Latin – despite the two languages not sharing exactly the same set of sounds – is like building a playroom using an IKEA office set.',
  'Modern buildings have to achieve certain performance requirements, at least to satisfy those of building codes, to provide a safe, healthy, and comfortable environment. However, these conditioned environments demand resources in energy and materials, which are both limited in supply, to build and operate.',
  'This finding is understandable in certain cases in spite of its high significance; that is because energy efficiency of building operation just represents a single aspect of sustainability.',
  "The insults and criticism were not unexpected. What was surprising was people's enthusiasm about the competition. Thousands have participated in the discussion.",
  'Who do you think is the most glamorous person? A biotechnologist who led his company in international research, an ordinary welder who gained international fame through his work, or a photographer complimented widely for a series of photos?',
  "In the photo, the wild cat's huge paws are clamped onto the side of the white safari Jeep in which Chappell was a passenger. Almost as tall as the Jeep on her hind legs, she appears to be forcing her muzzle into the back window.",
  'As far as politics go, the responses are just as varied. Mitigation is common and calls for a reduction of emissions and less reliance on fossil fuels. Coal burning power plants are now replaced with hydraulic power plants and electrical cars are replacing some gasoline efficient cars. Many people, however, feel that this is not enough.',
  'Unlike the United Kingdom, which has taken a relatively restrictive approach to the possession of arms, the United States has taken a more lenient approach. In the United States, three models have evolved regarding the interpretation of the meaning of the right to bear and keep arms as delineated in the Second Amendment.',
  'Smoking ban is a public policy that includes criminal laws and health regulations that prohibit smoking in certain public places and workspaces. There are varying definitions of smoking employed in this legislation.',
  'Welfare has a special political meaning to the United States because it refers to how the poor receives financial aid. In comparison, welfare services are regarded as a universal right in other regions like Europe, where it is believed that all citizens should be able to obtain a minimal level of social support and well-being.',
  'We acknowledge all the information and memory notes provided by students. We also acknowledge open source from various books and journal articles. All questions and answers are prepared and annotated by the Australian Institute of Language. All rights reserved.',
  'We have attempted to provide as accurate information as possible to assist all students with the exam preparation. Please note, however, that due to the accuracy of the memory, there may be subtle differences in words and phrases.',
  'Yellow is the most optimistic color, yet surprisingly, people lose their tempers most often in yellow rooms and babies cry more in them. The reason may be that yellow is the hardest color on the eye. On the other hand, it speeds metabolism and enhances concentration; think of yellow legal pads and post-it notes.',
  'Cheerful sunny yellow is an attention getter. While it is considered an optimistic color, people lose their tempers more often in yellow rooms, and babies will cry more. It is the most difficult color for the eye to take in, so it can be overpowering if overused.'
];

const FR_READING = [
  "Les Français sont très sympathiques et accueillants. Nous parlons français lorsque nous sommes dehors, à l'école ou au marché. Cependant, nous continuons de parler canadien à la maison, car mes parents ne veulent pas que je perde ma langue natale.",
  'Le rouge est une couleur vive. C’est la couleur de nombreux fruits et légumes, comme les tomates, les fraises ou les cerises. Le jaune est la couleur des bananes, du maïs ou des poussins par exemple. Le bleu est très présent dans la nature : c’est la couleur du ciel et de la mer. Le rouge, le jaune et le bleu sont les trois couleurs primaires.',
  'Je suis en vacances ! J’en profite pour faire une grasse-matinée et je sors de mon lit à dix heure. Je prends mon petit-déjeuner dans la cuisine. Je mange deux tartines de pain, un grand bol de café et un yaourt aux fruits rouges.',
  'Le lundi, David reste toute la journée à l’école. Souvent, le soir, il pratique une activité musicale : le piano. Le mardi ressemble au lundi sauf qu’il n’y a pas d’activité "après l’école, David rentre chez lui pour faire ses devoirs et se reposer. Il y a des régions où les enfants ne vont pas à l’école le mercredi.',
  "Puis, plus grand, je découvrais les métiers de policier et d'avocat dans un film. Je me disais alors que je voulais aussi combattre pour la justice. Je voulais poursuivre les criminels et défendre les gentils. Mais le monde ne fonctionne pas toujours ainsi.",
  'Pendant les grandes vacances, nous allons à la campagne chez mes grands-parents. Mon grand-père nous adore et nous offre de nombreux cadeaux. Ma tante Marcelline habite près "de chez eux. Parfois, ma grand-mère Marie l’invite à la maison pour le déjeuner. Elle vient avec son mari et mes cousins Lionel et Marcel.',
  "Le centre commercial est l'endroit idéal pour passer un bon moment avec sa famille, ses amis ou ses collègues de travail. Les gens y vont notamment pour déguster un bon hamburger assis près de la fontaine ou tout en regardant un spectacle de danse.",
  'Le jardin est long et étroit, il y a une balançoire au fond et un barbecue, proche de la terrasse, sur laquelle est posée un transat. Des chats viennent souvent chasser les feuilles qui volent au vent.',
  'Il s’apprête maintenant à prendre le funiculaire qui l’emmènera au sommet de la colline de Fourvière. Là, il pourra visiter la fameuse basilique Notre Dame de Fourvière et contempler la splendide vue panoramique sur la ville de Lyon depuis le belvédère.',
  "L'après-midi je me promène aux Tuileries, paradis de verdure au cœur de la capitale. Je suis fatiguée et préfère prendre le métro pour aller à l'Île de la Cité. En visitant la cathédrale Notre-Dame de Paris je pense à Quasimodo, personnage du roman de Victor Hugo.",
  'Je m’appelle John, je suis américain. Avec ma petite amie Jenny, nous passons une semaine de vacances à Paris. Comme je suis architecte, je veux profiter de notre séjour pour visiter le château de Versailles.',
  'Pâques est une fête catholique célébrée le 21 avril. Elle commémore la résurrection de Jésus mais fête aussi le printemps ! Tandis que les jonquilles fleurissent, les parents dissimulent du chocolat dans le jardin afin de célébrer Pâques.',
  'Les passants semblent moins pressés, et s’attardent plus facilement devant une devanture ou dans les rayons. Les dernières semaines avant Noël se déroulent dans une ambiance "joyeuse et féérique.',
  "Je m'appelle Angélica Summer, j'ai 12 ans et je suis canadienne. Il y a 5 ans, ma famille et moi avons déménagé dans le sud de la France.",
  'J’ai déjà pris l’avion car nous sommes allés à Rome en Italie, il y a deux ans. A Barcelone, mes parents ont réservé un appartement près de la plage. Mes parents souhaitent louer des vélos pour visiter Barcelone.'
];

export { EN_READING, FR_READING };
